name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ganti dengan branch yang sesuai jika perlu
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'  # Ganti dengan versi Go yang sesuai

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Build application
      run: |
        go build -o brevet-api ./cmd/server/main.go

    - name: Deploy to VPS
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}       # Username VPS (disimpan di Secrets)
          SERVER_IP: ${{ secrets.SERVER_IP }}           # IP Address VPS (disimpan di Secrets)
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}     # Password VPS (disimpan di Secrets)
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/brevet-api
            git pull origin main
            go build -o brevet-api ./cmd/server/main.go
            sudo systemctl restart brevet-api
          EOF
